pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "MafiaMaster"
include ':app'
include ':core:ui'
include ':data:players'
include ':feature:game'
include ':feature:game-setup'
include ':feature:games-archive'
include ':feature:players-data'
include ':feature:player-details'
include ':feature:roles-giving'
include ':feature:rules'
include ':feature:settings'