pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "MafiaMaster"
include ':app'
include ':core:ui'
include ':data:players'
include ':feature:game'
include ':feature:home'
include ':feature:players-data'
include ':feature:roles'
include ':feature:rules'
include ':feature:settings'